import { DocsSidebarProvider, useDocRootMetadata } from '@docusaurus/plugin-content-docs/client'
import type { Props } from '@theme/DocRoot'
import { useEffect } from 'react'
import { useDocsSidebarSync } from '../../contexts/DocsSidebarSync'

/** `docs.docRootComponent`. No local sidebar column here — the doc tree
 * renders in the PERSISTENT global sidebar instead (src/components/Sidebar.tsx),
 * merged with its "explore" section, so there's one sidebar on doc pages, not
 * two. `useEffect` pushes this route's `sidebarItems` up to that sidebar via
 * DocsSidebarSync (a plain second context — content-docs' own
 * `DocsSidebarProvider`/`useDocsSidebar()` only work INSIDE this subtree, and
 * the global sidebar is a sibling of it, not a descendant). NOT cleared on
 * unmount: the autogenerated sidebar is one static tree for the whole `/docs`
 * section (not per-page), so once it's loaded it stays visible in the global
 * sidebar even after navigating away — same always-on behavior as "explore".
 * A future multi-sidebar setup would need to revisit this.
 *
 * No `@theme/NotFound/Content` fallback for a missing route here (upstream
 * has one) — `onBrokenLinks: 'throw'` (docusaurus.config.ts) already fails
 * the build on a dangling doc link, so this case shouldn't reach runtime.
 *
 * Widened to max-w-[1180px] (was 820px) to make room for DocItem's right
 * "Asides" rail — the top links row and footer bar live IN DocItem, not
 * here, so they stay scoped to the content column instead of spanning full
 * width underneath the rail (see DocItem.tsx's comment). */
export default function DocRoot(props: Props) {
  const metadata = useDocRootMetadata(props)
  const { setItems } = useDocsSidebarSync()
  const sidebarItems = metadata?.sidebarItems ?? null

  useEffect(() => {
    if (sidebarItems) setItems(sidebarItems)
  }, [sidebarItems, setItems])

  if (!metadata) return null
  const { docElement, sidebarName } = metadata

  return (
    <DocsSidebarProvider name={sidebarName} items={metadata.sidebarItems}>
      <div className="mx-auto max-w-[1180px] px-12 py-10">{docElement}</div>
    </DocsSidebarProvider>
  )
}
