import Link from '@docusaurus/Link'
import type { PropSidebarItem } from '@docusaurus/plugin-content-docs'
import { useLocation } from '@docusaurus/router'

/** The doc-page-local sidebar (rendered by DocRoot.tsx, inside the content
 * pane) — a plain recursive renderer over content-docs' own sidebar data
 * (autogenerated from apps/docs/docs/, see sidebars.ts). This is DELIBERATELY
 * separate from src/components/Sidebar.tsx (the global, persistent one): this
 * one is contextual — it only exists while you're inside a doc page, for
 * moving BETWEEN doc pages, same idea as a page's own table of contents. */
export const DocSidebarItems = ({
  items,
  depth = 0,
}: {
  items: PropSidebarItem[]
  depth?: number
}) => {
  const location = useLocation()
  return (
    <ul className="m-0 list-none p-0" style={{ paddingLeft: depth ? '0.75rem' : 0 }}>
      {items.map((item) => {
        if (item.type === 'category') {
          return (
            <li key={item.label}>
              <div className="mt-3 mb-1 text-[0.68rem] font-bold uppercase tracking-[0.14em] text-dim">
                {item.label}
              </div>
              <DocSidebarItems items={item.items} depth={depth + 1} />
            </li>
          )
        }
        if (item.type === 'link') {
          const active = location.pathname.replace(/\/$/, '') === item.href.replace(/\/$/, '')
          return (
            <li key={item.href}>
              <Link
                to={item.href}
                className={`block border-l-2 py-1 pl-3 text-[0.82rem] no-underline hover:text-pop ${
                  active ? 'border-pop font-bold text-pop' : 'border-transparent text-ink'
                }`}
              >
                {item.label}
              </Link>
            </li>
          )
        }
        return null
      })}
    </ul>
  )
}
