import type { PropSidebarItem } from '@docusaurus/plugin-content-docs'
import { useLocation } from '@docusaurus/router'
import { type TreeItem, TreeItems } from '../CollapsibleTree'

const samePath = (a: string, b: string) => a.replace(/\/$/, '') === b.replace(/\/$/, '')

/** content-docs' own `PropSidebarItem[]` (autogenerated from apps/docs/docs/,
 * see sidebars.ts), adapted to the shared CollapsibleTree shape. `html` items
 * (raw sidebar HTML, unused today) are dropped rather than guessed at. */
const toTreeItems = (items: PropSidebarItem[], pathname: string): TreeItem[] =>
  items.flatMap((item): TreeItem[] => {
    if (item.type === 'category') {
      return [
        {
          type: 'category',
          key: item.label,
          label: item.label,
          items: toTreeItems(item.items, pathname),
        },
      ]
    }
    if (item.type === 'link') {
      return [
        {
          type: 'link',
          key: item.href,
          label: item.label,
          href: item.href,
          active: samePath(pathname, item.href),
        },
      ]
    }
    return []
  })

/** Feeds content-docs' sidebar data into the persistent global sidebar
 * (src/components/Sidebar.tsx) via CollapsibleTree — see the landing-page
 * skill for why there's no separate doc-page-local sidebar anymore. */
export const DocSidebarItems = ({ items }: { items: PropSidebarItem[] }) => {
  const location = useLocation()
  return <TreeItems items={toTreeItems(items, location.pathname)} />
}
