import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/* Autogenerated from apps/docs/docs/ — folder structure + sidebar_position
 * frontmatter decide order. No manual sidebar to keep in sync as pages are
 * added; see the landing-page skill for why this sidebar is separate from
 * the persistent one (src/theme/Root.tsx). */
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
